name: checker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  dotted_line: ^3.2.2
  badges: ^3.1.1
  flutter_easyloading: ^3.0.5
  dropdown_search: ^3.0.1
  awesome_dialog: ^3.1.0
  checkbox_grouped: ^1.8.2
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.2.1
  expansion_tile_group: ^1.2.0
  intl_phone_field: ^3.2.0

  # Animations
  flutter_bounce: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  rive: ^0.11.2
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  animations: ^2.0.7
  add_to_cart_animation: ^2.0.3
  like_button: ^2.0.5

  # Helpers
  flutter_screenutil: ^5.6.1
  flutter_dotenv: ^5.0.2
  flutter_keyboard_visibility: ^5.4.1
  mask_text_input_formatter: ^2.7.0
  vibration: ^1.7.4
  local_auth: ^2.1.6
  

  # State management
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1

   # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #cached_network_image: ^3.2.3

  # Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  requests_inspector: ^2.3.5

  # Localization
  easy_localization: ^3.0.1

  # Navigation
  go_router: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/riv/
    - .env
    
  
  fonts:

    - family: Stolzl
      fonts:
        - asset: assets/fonts/Stolzl-Bold.ttf   
          weight: 800
        - asset: assets/fonts/Stolzl-Book.ttf
          weight: 700
        - asset: assets/fonts/Stolzl-Light.ttf
          weight: 600
        - asset: assets/fonts/Stolzl-Regular.ttf
          weight: 500
        - asset: assets/fonts/Stolzl-Thin.ttf
          weight: 400
